### ISSUE TITLE
Write Readme

### ISSUE THREAD

**Issue by mjp59** [matthew-huber/bme590final#104]

**Comment by mjp59** [comment]
Wrote initial version of the readme. Feel free to read it and change anything. I focused on the core project mainly since that is what I worked on, so if you think a feature is under described, please add. Also ADD an EXTRA FEATURES, we added to the project. I mentioned some but I am not sure that is all of them

**Comment by mjp59** [comment]
@kofferdahl @matthew-huber

**Comment by matthew-huber** [comment]
Added my changes to the readme. @kofferdahl once you make your changes or give your approval I think we can close this issue.
