### ISSUE TITLE
Unit tests for server fails on Windows OS

### ISSUE THREAD

**Issue by kofferdahl** [matthew-huber/bme590final#107]
Because Windows and Mac/Linux encode numpy arrays differently, numpy arrays can't be used as tests because the expected outputs will depend on the OS. Instead, binary numbers should be passed into the tests, as these will be encoded in the same way.  See #64 for more details.

**Comment by kofferdahl** [comment]
@mjp59 I'm also getting failures on tests for Contrast Stretching, Log Compression, but I'm not sure if it's related or not. Are they working on your machine? We might not really need to test those since they do basically just call the built in function, but it is kind of weird that the tests aren't working for those.

**Comment by mjp59** [comment]
@kofferdahl those test also use numpy arrays. and everything was working on my machine, passed travis ci as well
