### ISSUE TITLE
GUI Crashs when I hit Process 

### ISSUE THREAD

**Issue by mjp59** [matthew-huber/bme590final#111]
Traceback (most recent call last):
  File "image_processor_gui.py", line 504, in process_button
    self.process_server()
  File "image_processor_gui.py", line 516, in process_server
    DB_filenames = self.makeDatabaseFileNames(fn, self.username)
AttributeError: 'App' object has no attribute 'makeDatabaseFileNames'
Abort trap: 6
(env) Michaels-MacBook-Pro-6:bme590final MichaelPostiglione$ python image_processor_gui.py
Traceback (most recent call last):
  File "image_processor_gui.py", line 504, in process_button
    self.process_server()
  File "image_processor_gui.py", line 516, in process_server
    DB_filenames = self.makeDatabaseFileNames(fn, self.username)
AttributeError: 'App' object has no attribute 'makeDatabaseFileNames'
Abort trap: 6

@kofferdahl Hey I just pulled the most recent master branch changes down to my computer. and the gui crashes when I click process. Here is the error I get.

**Comment by kofferdahl** [comment]
@mjp59  I think I know exactly what's wrong, and I should be able to fix it quickly. Sorry about that!

**Comment by kofferdahl** [comment]
@mjp59 it should be fixed now. Also, I had to comment out `matplotlib.use("QT5Agg")`  to get the Travis CI tests to work for some reason, so you and anyone else who uses mac will just have to uncomment those lines (we can include it in the readme)
