### ISSUE TITLE
What does reverse video mean in the context of this assignment?

### ISSUE THREAD

**Issue by kofferdahl** [matthew-huber/bme590final#19]
The assignment specifications indicate that the image processor should be able to 'Reverse Video.' Does this mean that the image processor also needs to be able to handle videos? Or does reversing videos simply mean reversing the order of a set of images given to it?

**Comment by mlp6** [comment]
"Reverse Video" refers to inverting the dark and bright in a grayscale image.  Note that means that this operating only applies to a certain type of image... which was done on purpose. ;)

**Comment by kofferdahl** [comment]
@mlp6  when checking to see if it is a grayscale image, is it reasonable to assume that a grayscale image will always be 2D, and if its 3D its a color image? Or do we need to check to see if it's secretly a grayscale image with 3D (by checking to see if the R, G, and B pixel values are always equal for each point in the image)?

**Comment by kofferdahl** [comment]
@mlp6  nevermind, I just went ahead and did both cases just in case. Thank you!!
