### ISSUE TITLE
Processing selection

### ISSUE THREAD

**Issue by matthew-huber** [matthew-huber/bme590final#3]
Provide a dropdown menu or radio button selection option to chose between Histogram Equalization, Contrast Stretching, Log Compression, Reverse Video, or other processing functions. A `Process` button will trigger the selected option to run.

**Comment by matthew-huber** [comment]
Uploading files to flask:
http://flask.pocoo.org/docs/1.0/patterns/fileuploads/

**Comment by mjp59** [comment]
Dropdown menu complete
