### ISSUE TITLE
GUI can't handle 2D images

### ISSUE THREAD

**Issue by kofferdahl** [matthew-huber/bme590final#31]
Some images, like GS_2D.png in the TestImages folder, are 2 dimensional because they are grayscale intensities (and therefore don't need a third dimension). This throws a  ValueError in the image_processor_gui when one tries to open an image like GS_2D.png.

Here's a link to the line where image_processor_gui.py throws an error at [line 66](https://github.com/matthew-huber/bme590final/blob/1fe37462ae76d71c69138d66ddc087f50bd62c4f/image_processor_gui.py#L66)

**Comment by mjp59** [comment]
@matthew-huber can unpack with out breaking code now. Can't display 2D images though on GUI. Fix this instead.
