### ISSUE TITLE
The server does not currently receive the user's username from the GUI

### ISSUE THREAD

**Issue by kofferdahl** [matthew-huber/bme590final#41]
The username is a part of the metadata associated with the image in the database, but currently the server does not get it from the GUI, so it can't be added to the databsase. 

The addImagesToDatabase function in image_processor_server.py currently has "Placeholder" where the username will eventually go: https://github.com/matthew-huber/bme590final/blob/ac9d41f222cef7b7177acd66a0736537196b34a3/image_processor_server.py#L144

**Comment by matthew-huber** [comment]
The gui version I'm working on in reformat_gui can access the entered username and will send them in the upload post request
