### ISSUE TITLE
What is the best way to check to see if an object is already in the database based on it's primary key?

### ISSUE THREAD

**Issue by kofferdahl** [matthew-huber/bme590final#44]
I want to be able to check to see if an object is already in the database, and only create a new one if it doesn't exist. The code I currently have for doing this can be found here https://github.com/matthew-huber/bme590final/blob/e1879e14b3960a1fd31b520eb3368227d81808c5/image_processor_server.py#L153 but it doesn't feel like the best way to do such an obvious database function. 

I would feel better about my approach if the except clause only caught the DoesNotExist exception rather than catching any exception, but I can't figure out how to catch an exception like that when it isn't one of the built in exceptions. The traceback for the exception looks like this:

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\koffe\BME590\bme590final\.venv\lib\site-packages\pymodm\queryset.py", line 129, in first
    raise self._model.DoesNotExist()
img_db.DoesNotExist`

**Comment by mlp6** [comment]
Definitely want to use an explicit exception code.  I'm not familiar with what `pymodm` might raise; can you add @suyashkumar to this repo and get his input here?

**Comment by suyashkumar** [comment]
something else that also avoids doing this check a lot is using a UUIDv4 as a primary key (uniquely generated key for each image) which means you can just store a newly uploaded image again in a new spot and associate that UUID with that image if the user happened to upload the image twice. You can also go down the route you are going now if you would like!

**Comment by dward2** [comment]
I know this is late and I'm sorry I missed this thread the first time around.  But, just from a learning perspective, I wanted to share that to have access to the MongoDB exceptions, import `errors` from `pymodm` like:
```
from pymodm import errors
```
Then, you will have access to the `errors.DoesNotExist` exception so you can do:
```
try:
    # your code to try here
except errors.DoesNotExist:
    # your exception code here
```

**Comment by kofferdahl** [comment]
@dward2 thank you so much for following up! I've encountered this problem in other projects too, so it's really nice to know how to fix it.
