### ISSUE TITLE
break up different image processing functions into stand-alone functions

### ISSUE THREAD

**Issue by mlp6** [matthew-huber/bme590final#46]
https://github.com/matthew-huber/bme590final/blob/e1879e14b3960a1fd31b520eb3368227d81808c5/image_processor_server.py#L51

that way you can test each one explicitly

you also do similar reshaping for each function; break that out into its own function that can be called before each image processing step

**Comment by kofferdahl** [comment]
@mjp59  Are you okay with me refactoring your code here, or would you prefer to do it?

**Comment by mjp59** [comment]
@kofferdahl you can go ahead and do it. Let me know if you have any questions
