### ISSUE TITLE
Display Image metadata

### ISSUE THREAD

**Issue by matthew-huber** [matthew-huber/bme590final#6]
Display on GUI the image metadata stored in the server. The display should contain the timestamp of the uploaded image, the time it took to process the image, and the image size in pixels.

**Comment by kofferdahl** [comment]
How should we keep track of users on the server (e.g. d we have people enter in some kind of user name, make a new user for each session even if it might be the same person between sessions, or some fancy way to figure out if its a new person with IP addresses or something)?

Should the time stamps be made by the Image Processor object (back end) or when the front end calls these back end functions?

**Comment by matthew-huber** [comment]
Covered with addition of manage images tab
