### ISSUE TITLE
Add functionality to save the processed images when the user hits the download button

### ISSUE THREAD

**Issue by kofferdahl** [matthew-huber/bme590final#69]
Images need to be able to saved as JPEG, PNG, or TIFF.
Processed images will be saved in the same location as the original images, with processing type appended to the file name (e.g original_file --> original_file_histogramEqualization)

**Comment by matthew-huber** [comment]
I think this is the same issue referenced in #12 and #7?

**Comment by kofferdahl** [comment]
You're right - sorry, I didn't realize we already had open issues for this.
