### ISSUE TITLE
gui crashs one image or no images are selected and the prev and next buttons are hit

### ISSUE THREAD

**Issue by mjp59** [matthew-huber/bme590final#75]
Prev and next buttons remain active after a list is selected. Then when an individual image is selected, the buttons can be clicked causing the gui to crash.

**Comment by matthew-huber** [comment]
I'm having trouble replicating this error. Remind me about it when we're together tomorrow, and you can show me. Thanks!

**Comment by mjp59** [comment]
Looks like it is fixed already. Good job!
