### ISSUE TITLE
Image pre-processor which takes in input string from GUI, validates & formats it for image processor 

### ISSUE THREAD

**Issue by kofferdahl** [matthew-huber/bme590final#8]
The File Selector (#1) will pass the selected image, list of images, or .zip file to the pre-processor. The pre-processor will then validate the file paths and ensure that the images are of a valid data type, raising exceptions that will be handled by the GUI if the inputs are not valid. The pre-processor will compile a list of file path strings, which will be used to initialize an image processor object. This will involve handling the zip file by getting a list of images from it (and unzipping if necessary). 

The pre-processor will then create a scikit-image Collection that can be fed into the image processor's processing functions.

**Comment by mjp59** [comment]
currently sent up to base64 encode images and get string of image processing command. Put these things in dict then send as a json
