### ISSUE TITLE
Code in image_processor_gui.py and image_processor_server.py is not very modular. 

### ISSUE THREAD

**Issue by kofferdahl** [matthew-huber/bme590final#89]
The code in most of the functions here should be modularized, and unit tests for those more modular functions should be added.

**Comment by mjp59** [comment]
@kofferdahl I just started playing around with gui more to test it with remote server and some stuff on the gui is behaving improperly and the gui is breaking. Can we meet to figure out what in the modular version of the gui is breaking/ not function as excepted. I have class from 3-4 today, but can meet any other time today or sometime this weekend

**Comment by kofferdahl** [comment]
@mjp59  Yeah we can do that. I'm available either this evening (after about 6:00 PM) or anything this weekend. How is it behaving improperly / breaking?

**Comment by mjp59** [comment]
@kofferdahl I can meet you in e-quad. We can just work in hudson hall.

**Comment by kofferdahl** [comment]
@mjp56 okay! E-quad is the quad outside Hudson? My phone number is 775-303-3241 in case anything changes
